### ISSUE TITLE
OOAnalyzer plugin will not compile with Ghidra 9.1

### ISSUE THREAD

**Issue by wdormann** [cmu-sei/pharos#56]
The OOAnalyzer Ghidra plugin doesn't seem to compile with Ghidra 9.1   The same environment builds against Ghidra 9.04 just fine.

```
gradle -PGHIDRA_INSTALL_DIR=/home/tapioca/in/ghidra_9.1_PUBLIC

> Task :compileJava FAILED
/home/tapioca/in/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/OOAnalyzer.java:1406: error: no suitable constructor found for OptionDialog(String,String,String,int,<null>)
                                var contDialog = new OptionDialog("Careful",
                                                 ^
    constructor OptionDialog.OptionDialog(String,String,int,Icon) is not applicable
      (actual and formal argument lists differ in length)
    constructor OptionDialog.OptionDialog(String,String,String,String,int,Icon,boolean) is not applicable
      (actual and formal argument lists differ in length)
    constructor OptionDialog.OptionDialog(String,String,String,String,int,Icon,boolean,String) is not applicable
      (actual and formal argument lists differ in length)
    constructor OptionDialog.OptionDialog(String,String,String,int,Icon,String) is not applicable
      (actual and formal argument lists differ in length)
    constructor OptionDialog.OptionDialog(String,String,String,String,String,int,Icon,boolean) is not applicable
      (actual and formal argument lists differ in length)
    constructor OptionDialog.OptionDialog(String,String,int,Icon,boolean,DialogRememberOption,List<String>,String) is not applicable
      (actual and formal argument lists differ in length)
/home/tapioca/in/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/OOAnalyzerGhidraPlugin.java:64: error: no suitable constructor found for OptionDialog(String,String,int,<null>)
                        new OptionDialog("Error", "Invalid JSON file", OptionDialog.ERROR_MESSAGE, null).show();
                        ^
    constructor OptionDialog.OptionDialog(String,String,String,String,int,Icon,boolean) is not applicable
      (actual and formal argument lists differ in length)
    constructor OptionDialog.OptionDialog(String,String,String,String,int,Icon,boolean,String) is not applicable
      (actual and formal argument lists differ in length)
    constructor OptionDialog.OptionDialog(String,String,String,int,Icon) is not applicable
      (actual and formal argument lists differ in length)
    constructor OptionDialog.OptionDialog(String,String,String,int,Icon,String) is not applicable
      (actual and formal argument lists differ in length)
    constructor OptionDialog.OptionDialog(String,String,String,String,String,int,Icon,boolean) is not applicable
      (actual and formal argument lists differ in length)
    constructor OptionDialog.OptionDialog(String,String,int,Icon,boolean,DialogRememberOption,List<String>,String) is not applicable
      (actual and formal argument lists differ in length)
/home/tapioca/in/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/OOAnalyzerGhidraPlugin.java:74: error: no suitable constructor found for OptionDialog(String,String,int,<null>)
                        new OptionDialog("Error", "Could not load/parse JSON file " + jsonFile.getName(),
                        ^
    constructor OptionDialog.OptionDialog(String,String,String,String,int,Icon,boolean) is not applicable
      (actual and formal argument lists differ in length)
    constructor OptionDialog.OptionDialog(String,String,String,String,int,Icon,boolean,String) is not applicable
      (actual and formal argument lists differ in length)
    constructor OptionDialog.OptionDialog(String,String,String,int,Icon) is not applicable
      (actual and formal argument lists differ in length)
    constructor OptionDialog.OptionDialog(String,String,String,int,Icon,String) is not applicable
      (actual and formal argument lists differ in length)
    constructor OptionDialog.OptionDialog(String,String,String,String,String,int,Icon,boolean) is not applicable
      (actual and formal argument lists differ in length)
    constructor OptionDialog.OptionDialog(String,String,int,Icon,boolean,DialogRememberOption,List<String>,String) is not applicable
      (actual and formal argument lists differ in length)
/home/tapioca/in/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/OOAnalyzerGhidraPlugin.java:87: error: no suitable constructor found for OptionDialog(String,String,int,<null>)
                                                new OptionDialog("Error", "No current program for OOAnalyzer.", OptionDialog.ERROR_MESSAGE,
                                                ^
    constructor OptionDialog.OptionDialog(String,String,String,String,int,Icon,boolean) is not applicable
      (actual and formal argument lists differ in length)
    constructor OptionDialog.OptionDialog(String,String,String,String,int,Icon,boolean,String) is not applicable
      (actual and formal argument lists differ in length)
    constructor OptionDialog.OptionDialog(String,String,String,int,Icon) is not applicable
      (actual and formal argument lists differ in length)
    constructor OptionDialog.OptionDialog(String,String,String,int,Icon,String) is not applicable
      (actual and formal argument lists differ in length)
    constructor OptionDialog.OptionDialog(String,String,String,String,String,int,Icon,boolean) is not applicable
      (actual and formal argument lists differ in length)
    constructor OptionDialog.OptionDialog(String,String,int,Icon,boolean,DialogRememberOption,List<String>,String) is not applicable
      (actual and formal argument lists differ in length)
/home/tapioca/in/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/OOAnalyzerGhidraPlugin.java:90: error: no suitable constructor found for OptionDialog(String,String,int,<null>)
                                                new OptionDialog("Results", "OOAnalyzer loaded " + result + " classes.", 
                                                ^
    constructor OptionDialog.OptionDialog(String,String,String,String,int,Icon,boolean) is not applicable
      (actual and formal argument lists differ in length)
    constructor OptionDialog.OptionDialog(String,String,String,String,int,Icon,boolean,String) is not applicable
      (actual and formal argument lists differ in length)
    constructor OptionDialog.OptionDialog(String,String,String,int,Icon) is not applicable
      (actual and formal argument lists differ in length)
    constructor OptionDialog.OptionDialog(String,String,String,int,Icon,String) is not applicable
      (actual and formal argument lists differ in length)
    constructor OptionDialog.OptionDialog(String,String,String,String,String,int,Icon,boolean) is not applicable
      (actual and formal argument lists differ in length)
    constructor OptionDialog.OptionDialog(String,String,int,Icon,boolean,DialogRememberOption,List<String>,String) is not applicable
      (actual and formal argument lists differ in length)
/home/tapioca/in/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/OOAnalyzerGhidraPlugin.java:93: error: no suitable constructor found for OptionDialog(String,String,int,<null>)
                                                new OptionDialog("Results", "OOAnalyzer could not load any classes",
                                                ^
    constructor OptionDialog.OptionDialog(String,String,String,String,int,Icon,boolean) is not applicable
      (actual and formal argument lists differ in length)
    constructor OptionDialog.OptionDialog(String,String,String,String,int,Icon,boolean,String) is not applicable
      (actual and formal argument lists differ in length)
    constructor OptionDialog.OptionDialog(String,String,String,int,Icon) is not applicable
      (actual and formal argument lists differ in length)
    constructor OptionDialog.OptionDialog(String,String,String,int,Icon,String) is not applicable
      (actual and formal argument lists differ in length)
    constructor OptionDialog.OptionDialog(String,String,String,String,String,int,Icon,boolean) is not applicable
      (actual and formal argument lists differ in length)
    constructor OptionDialog.OptionDialog(String,String,int,Icon,boolean,DialogRememberOption,List<String>,String) is not applicable
      (actual and formal argument lists differ in length)
6 errors


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
2 actionable tasks: 1 executed, 1 up-to-date

```

**Comment by jeffgennari** [comment]
Thanks for the report. We have a fix for this that is just about ready for public release.

**Comment by KevinPoole** [comment]
Any timeline on release? Just ran into this as well :(

**Comment by sei-jgennari** [comment]
This should
