### ISSUE TITLE
Extension version for <OOAnalyzerPlugin> is incompatible with Ghidra 9.1.2

### ISSUE THREAD

**Issue by josekahu** [cmu-sei/pharos#64]
Am getting with error message when i try to install the plugin

**Comment by jeffgennari** [comment]
Can you be a little more specific on the error you are seeing? I confirmed that the plugin builds in Ghidra 9.1.2_PUBLIC. Note that if you are trying to use a version of the plugin built with a previous version of Ghidra, then you will need to rebuild with 9.1.2_PUBLIC.

**Comment by josekahu** [comment]
Please, give us a write up on how to do it on 9.1.2, am building it but i get incompatible error.

**Comment by josekahu** [comment]
Is it possible to share build zip file

**Comment by Sinderella** [comment]
I can build it with gradle just fine with ghidra 9.1.2. You also need to specify the path to ghidra.
I simply followed these commands in the comment. The zip file should be produced in the `dist` directory.

https://github.com/cmu-sei/pharos/blob/master/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/build.gradle#L6-L11
```
//     > export GHIDRA_INSTALL_DIR=<Absolute path to Ghidra> 
//     > gradle
//
//         or
//
//     > gradle -PGHIDRA_INSTALL_DIR=<Absolute path to Ghidra>
```

**Comment by ryancor** [comment]
I can build it just fine as well with the path to Ghidra 9.1.2 but when trying to run the plugin, i get no popup to input a JSON file

**Comment by josekahu** [comment]
Upload the zip file,  please it has refused to build

**Comment by sei-eschwartz** [comment]
@josekahu Can you post an error log?

**Comment by advaithm** [comment]
using the zip file from the repo also does not work

**Comment by jeffgennari** [comment]
Can you please provide more details, which version of Ghidra? What are the build errors?

**Comment by advaithm** [comment]
Ghidra 9.1.2
the error when compiling
```
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/OOAnalyzerType.java:11: error: package com.google.gson does not exist
import com.google.gson.JsonArray;
                      ^
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/OOAnalyzerType.java:12: error: package com.google.gson.annotations does not exist
import com.google.gson.annotations.Expose;
                                  ^
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/OOAnalyzerType.java:13: error: package com.google.gson.annotations does not exist
import com.google.gson.annotations.SerializedName;
                                  ^
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/Member.java:8: error: package com.google.gson.annotations does not exist
import com.google.gson.annotations.Expose;
                                  ^
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/Member.java:9: error: package com.google.gson.annotations does not exist
import com.google.gson.annotations.SerializedName;
                                  ^
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/Method.java:6: error: package com.google.gson.annotations does not exist
import com.google.gson.annotations.Expose;
                                  ^
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/Method.java:7: error: package com.google.gson.annotations does not exist
import com.google.gson.annotations.SerializedName;
                                  ^
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/Vftable.java:10: error: package com.google.gson.annotations does not exist
import com.google.gson.annotations.Expose;
                                  ^
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/Vftable.java:11: error: package com.google.gson.annotations does not exist
import com.google.gson.annotations.JsonAdapter;
                                  ^
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/Vftable.java:12: error: package com.google.gson.annotations does not exist
import com.google.gson.annotations.SerializedName;
                                  ^
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/Vfentry.java:7: error: package com.google.gson.annotations does not exist
import com.google.gson.annotations.Expose;
                                  ^
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/Vfentry.java:8: error: package com.google.gson.annotations does not exist
import com.google.gson.annotations.JsonAdapter;
                                  ^
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/Vfentry.java:9: error: package com.google.gson.annotations does not exist
import com.google.gson.annotations.SerializedName;
                                  ^
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/OOAnalyzerClassList.java:15: error: package com.google.gson.annotations does not exist
import com.google.gson.annotations.Expose;
                                  ^
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/OOAnalyzerClassList.java:16: error: package com.google.gson.annotations does not exist
import com.google.gson.annotations.SerializedName;
                                  ^
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/OOAnalyzer.java:28: error: package com.google.gson does not exist
import com.google.gson.Gson;
                      ^
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/OOAnalyzer.java:29: error: package com.google.gson does not exist
import com.google.gson.GsonBuilder;
                      ^
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/OOAnalyzer.java:30: error: package com.google.gson does not exist
import com.google.gson.JsonDeserializationContext;
                      ^
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/OOAnalyzer.java:31: error: package com.google.gson does not exist
import com.google.gson.JsonDeserializer;
                      ^
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/OOAnalyzer.java:32: error: package com.google.gson does not exist
import com.google.gson.JsonElement;
                      ^
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/OOAnalyzer.java:33: error: package com.google.gson does not exist
import com.google.gson.JsonObject;
                      ^
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/OOAnalyzer.java:34: error: package com.google.gson does not exist
import com.google.gson.JsonParseException;
                      ^
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/OOAnalyzer.java:35: error: package com.google.gson does not exist
import com.google.gson.JsonSyntaxException;
                      ^
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/OOAnalyzer.java:36: error: package com.google.gson.reflect does not exist
import com.google.gson.reflect.TypeToken;
                              ^
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/OOAnalyzer.java:37: error: package com.google.gson.stream does not exist
import com.google.gson.stream.JsonReader;
                             ^
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/OOAnalyzerType.java:24: error: cannot find symbol
        @Expose
         ^
  symbol:   class Expose
  location: class OOAnalyzerType
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/OOAnalyzerType.java:25: error: cannot find symbol
        @SerializedName("Name")
         ^
  symbol:   class SerializedName
  location: class OOAnalyzerType
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/OOAnalyzerType.java:28: error: cannot find symbol
        @Expose
         ^
  symbol:   class Expose
  location: class OOAnalyzerType
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/OOAnalyzerType.java:29: error: cannot find symbol
        @SerializedName("DemangledName")
         ^
  symbol:   class SerializedName
  location: class OOAnalyzerType
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/OOAnalyzerType.java:35: error: cannot find symbol
        @Expose
         ^
  symbol:   class Expose
  location: class OOAnalyzerType
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/OOAnalyzerType.java:36: error: cannot find symbol
        @SerializedName("Size")
         ^
  symbol:   class SerializedName
  location: class OOAnalyzerType
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/OOAnalyzerType.java:39: error: cannot find symbol
        @Expose
         ^
  symbol:   class Expose
  location: class OOAnalyzerType
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/OOAnalyzerType.java:40: error: cannot find symbol
        @SerializedName("Members")
         ^
  symbol:   class SerializedName
  location: class OOAnalyzerType
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/OOAnalyzerType.java:43: error: cannot find symbol
        @Expose
         ^
  symbol:   class Expose
  location: class OOAnalyzerType
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/OOAnalyzerType.java:44: error: cannot find symbol
        @SerializedName("Methods")
         ^
  symbol:   class SerializedName
  location: class OOAnalyzerType
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/OOAnalyzerType.java:47: error: cannot find symbol
        @Expose
         ^
  symbol:   class Expose
  location: class OOAnalyzerType
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/OOAnalyzerType.java:48: error: cannot find symbol
        @SerializedName("Vftables")
         ^
  symbol:   class SerializedName
  location: class OOAnalyzerType
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/Vftable.java:19: error: cannot find symbol
        @Expose
         ^
  symbol:   class Expose
  location: class Vftable
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/Vftable.java:20: error: cannot find symbol
        @SerializedName("ea")
         ^
  symbol:   class SerializedName
  location: class Vftable
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/Vftable.java:23: error: cannot find symbol
        @Expose
         ^
  symbol:   class Expose
  location: class Vftable
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/Vftable.java:24: error: cannot find symbol
        @SerializedName("vfptr")
         ^
  symbol:   class SerializedName
  location: class Vftable
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/Vftable.java:27: error: cannot find symbol
        @Expose
         ^
  symbol:   class Expose
  location: class Vftable
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/Vftable.java:28: error: cannot find symbol
        @SerializedName("entries")
         ^
  symbol:   class SerializedName
  location: class Vftable
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/Vfentry.java:17: error: cannot find symbol
        @Expose
         ^
  symbol:   class Expose
  location: class Vfentry
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/Vfentry.java:18: error: cannot find symbol
        @SerializedName("ea")
         ^
  symbol:   class SerializedName
  location: class Vfentry
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/Vfentry.java:21: error: cannot find symbol
        @Expose
         ^
  symbol:   class Expose
  location: class Vfentry
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/Vfentry.java:22: error: cannot find symbol
        @SerializedName("offset")
         ^
  symbol:   class SerializedName
  location: class Vfentry
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/Vfentry.java:25: error: cannot find symbol
        @Expose
         ^
  symbol:   class Expose
  location: class Vfentry
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/Vfentry.java:26: error: cannot find symbol
        @SerializedName("name")
         ^
  symbol:   class SerializedName
  location: class Vfentry
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/Vfentry.java:29: error: cannot find symbol
        @Expose
         ^
  symbol:   class Expose
  location: class Vfentry
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/Vfentry.java:30: error: cannot find symbol
        @SerializedName("demangled_name")
         ^
  symbol:   class SerializedName
  location: class Vfentry
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/Vfentry.java:33: error: cannot find symbol
        @Expose
         ^
  symbol:   class Expose
  location: class Vfentry
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/Vfentry.java:34: error: cannot find symbol
        @SerializedName("import")
         ^
  symbol:   class SerializedName
  location: class Vfentry
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/Vfentry.java:37: error: cannot find symbol
        @Expose
         ^
  symbol:   class Expose
  location: class Vfentry
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/Vfentry.java:38: error: cannot find symbol
        @SerializedName("type")
         ^
  symbol:   class SerializedName
  location: class Vfentry
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/Method.java:14: error: cannot find symbol
        @Expose
         ^
  symbol:   class Expose
  location: class Method
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/Method.java:15: error: cannot find symbol
        @SerializedName("ea")
         ^
  symbol:   class SerializedName
  location: class Method
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/Method.java:18: error: cannot find symbol
        @Expose
         ^
  symbol:   class Expose
  location: class Method
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/Method.java:19: error: cannot find symbol
        @SerializedName("type")
         ^
  symbol:   class SerializedName
  location: class Method
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/Method.java:22: error: cannot find symbol
        @Expose
         ^
  symbol:   class Expose
  location: class Method
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/Method.java:23: error: cannot find symbol
        @SerializedName("name")
         ^
  symbol:   class SerializedName
  location: class Method
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/Method.java:26: error: cannot find symbol
        @Expose
         ^
  symbol:   class Expose
  location: class Method
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/Method.java:27: error: cannot find symbol
        @SerializedName("demangled_name")
         ^
  symbol:   class SerializedName
  location: class Method
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/Method.java:30: error: cannot find symbol
        @Expose
         ^
  symbol:   class Expose
  location: class Method
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/Method.java:31: error: cannot find symbol
        @SerializedName("import")
         ^
  symbol:   class SerializedName
  location: class Method
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/Member.java:18: error: cannot find symbol
    @Expose
     ^
  symbol:   class Expose
  location: class Member
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/Member.java:19: error: cannot find symbol
    @SerializedName("name")
     ^
  symbol:   class SerializedName
  location: class Member
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/Member.java:22: error: cannot find symbol
    @Expose
     ^
  symbol:   class Expose
  location: class Member
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/Member.java:23: error: cannot find symbol
    @SerializedName("type")
     ^
  symbol:   class SerializedName
  location: class Member
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/Member.java:26: error: cannot find symbol
    @Expose
     ^
  symbol:   class Expose
  location: class Member
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/Member.java:27: error: cannot find symbol
    @SerializedName("struc")
     ^
  symbol:   class SerializedName
  location: class Member
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/Member.java:30: error: cannot find symbol
    @Expose
     ^
  symbol:   class Expose
  location: class Member
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/Member.java:31: error: cannot find symbol
    @SerializedName("parent")
     ^
  symbol:   class SerializedName
  location: class Member
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/Member.java:34: error: cannot find symbol
    @Expose
     ^
  symbol:   class Expose
  location: class Member
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/Member.java:35: error: cannot find symbol
    @SerializedName("offset")
     ^
  symbol:   class SerializedName
  location: class Member
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/Member.java:38: error: cannot find symbol
    @Expose
     ^
  symbol:   class Expose
  location: class Member
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/Member.java:39: error: cannot find symbol
    @SerializedName("count")
     ^
  symbol:   class SerializedName
  location: class Member
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/OOAnalyzerClassList.java:23: error: cannot find symbol
        @SerializedName("Structures")
         ^
  symbol:   class SerializedName
  location: class OOAnalyzerClassList
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/jsontypes/OOAnalyzerClassList.java:24: error: cannot find symbol
        @Expose
         ^
  symbol:   class Expose
  location: class OOAnalyzerClassList
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/OOAnalyzer.java:1411: error: cannot find symbol
                        JsonReader reader = null;
                        ^
  symbol:   class JsonReader
  location: class OOAnalyzer
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/OOAnalyzer.java:1415: error: cannot find symbol
                                reader = new JsonReader(new FileReader(jsonFile));
                                             ^
  symbol:   class JsonReader
  location: class OOAnalyzer
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/OOAnalyzer.java:1420: error: cannot find symbol
                                JsonDeserializer<OOAnalyzerType> deserializer = new JsonDeserializer<OOAnalyzerType>() {
                                ^
  symbol:   class JsonDeserializer
  location: class OOAnalyzer
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/OOAnalyzer.java:1420: error: cannot find symbol
                                JsonDeserializer<OOAnalyzerType> deserializer = new JsonDeserializer<OOAnalyzerType>() {
                                                                                    ^
  symbol:   class JsonDeserializer
  location: class OOAnalyzer
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/OOAnalyzer.java:1423: error: cannot find symbol
                                        public OOAnalyzerType deserialize(JsonElement json, Type typeOfT,
                                                                          ^
  symbol: class JsonElement
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/OOAnalyzer.java:1424: error: cannot find symbol
                                                        JsonDeserializationContext context) throws JsonParseException {
                                                        ^
  symbol: class JsonDeserializationContext
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/OOAnalyzer.java:1424: error: cannot find symbol
                                                        JsonDeserializationContext context) throws JsonParseException {
                                                                                                   ^
  symbol: class JsonParseException
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/OOAnalyzer.java:1422: error: method does not override or implement a method from a supertype
                                        @Override
                                        ^
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/OOAnalyzer.java:1426: error: cannot find symbol
                                                JsonObject jsonObject = json.getAsJsonObject();
                                                ^
  symbol: class JsonObject
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/OOAnalyzer.java:1452: error: cannot find symbol
                                                                JsonElement jElm = jsonObject.get(demangledNameJSONString);
                                                                ^
  symbol: class JsonElement
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/OOAnalyzer.java:1463: error: cannot find symbol
                                                Gson g = new Gson();
                                                ^
  symbol: class Gson
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/OOAnalyzer.java:1463: error: cannot find symbol
                                                Gson g = new Gson();
                                                             ^
  symbol: class Gson
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/OOAnalyzer.java:1465: error: cannot find symbol
                                                Type mbrListType = new TypeToken<List<Member>>() {
                                                                       ^
  symbol: class TypeToken
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/OOAnalyzer.java:1469: error: cannot find symbol
                                                } catch (JsonSyntaxException | IllegalStateException mbrx) {
                                                         ^
  symbol: class JsonSyntaxException
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/OOAnalyzer.java:1473: error: cannot find symbol
                                                Type mthListType = new TypeToken<List<Method>>() {
                                                                       ^
  symbol: class TypeToken
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/OOAnalyzer.java:1477: error: cannot find symbol
                                                } catch (JsonSyntaxException | IllegalStateException mthx) {
                                                         ^
  symbol: class JsonSyntaxException
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/OOAnalyzer.java:1481: error: cannot find symbol
                                                Type vftListType = new TypeToken<List<Vftable>>() {
                                                                       ^
  symbol: class TypeToken
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/OOAnalyzer.java:1485: error: cannot find symbol
                                                } catch (JsonSyntaxException | IllegalStateException vftx) {
                                                         ^
  symbol: class JsonSyntaxException
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/OOAnalyzer.java:1493: error: cannot find symbol
                                GsonBuilder gsonBuilder = new GsonBuilder();
                                ^
  symbol:   class GsonBuilder
  location: class OOAnalyzer
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/OOAnalyzer.java:1493: error: cannot find symbol
                                GsonBuilder gsonBuilder = new GsonBuilder();
                                                              ^
  symbol:   class GsonBuilder
  location: class OOAnalyzer
/home/advaithm/Desktop/wanacry/pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/src/main/java/ooanalyzer/OOAnalyzer.java:1495: error: cannot find symbol
                                Gson gson = gsonBuilder.excludeFieldsWithoutExposeAnnotation().create();
                                ^
  symbol:   class Gson
  location: class OOAnalyzer
100 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
```

**Comment by Sinderella** [comment]
Did you perhaps forget to download the dependency?

https://github.com/cmu-sei/pharos/tree/master/tools/ooanalyzer/ghidra/OOAnalyzerPlugin#building-the-plugin
```
cd pharos/tools/ooanalyzer/ghidra/OOAnalyzerPlugin/lib/
wget https://repo1.maven.org/maven2/com/google/code/gson/gson/2.8.5/gson-2.8.5.jar
```

**Comment by advaithm** [comment]
i am sorry i forgot to get the dependency but there is still a warning 
```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
```

**Comment by Sinderella** [comment]
I think the warning can be safely ignored as long as you are not using Gradle 7.0, which I think is not released yet. I did get the same warning, but it also produced the working plugin.
The build should be successful, can you check the `dist` folder?

I am not one of the developers, just a user as well. 😆

**Comment by advaithm** [comment]
the plugin works now

**Comment by sei-eschwartz** [comment]
Thanks @Sinderella for helping out.
